/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jamie' at '30/01/17 21:33' with Gradle 3.0
 *
 * @author Jamie, @date 30/01/17 21:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
